import type { Product } from "./productType";

export const products: Product[] = [
  {
    id: 1,
    name: "iPhone 15 Pro Max",
    category: "Smartphones",
    brand: "Apple",
    price: 1199,
    discountPrice: 1099,
    rating: 4.9,
    reviews: 128,
    image: "/iphone-15-pro-max.png",
    tag: "Best Seller",
    inStock: true,
  },
  {
    id: 2,
    name: "MacBook Pro M3",
    category: "Laptops",
    brand: "Apple",
    price: 2399,
    discountPrice: null,
    rating: 4.8,
    reviews: 89,
    image: "/macbook-pro-laptop-silver.jpg",
    tag: "New Arrival",
    inStock: true,
  },
  {
    id: 3,
    name: "Samsung Galaxy S24 Ultra",
    category: "Smartphones",
    brand: "Samsung",
    price: 1299,
    discountPrice: 1199,
    rating: 4.7,
    reviews: 156,
    image: "/samsung-galaxy-s24-ultra.png",
    tag: "Hot Deal",
    inStock: true,
  },
  {
    id: 4,
    name: "AirPods Pro 2nd Gen",
    category: "Audio",
    brand: "Apple",
    price: 249,
    discountPrice: 199,
    rating: 4.6,
    reviews: 203,
    image: "/apple-airpods-pro-white-earbuds.png",
    tag: "Limited Offer",
    inStock: true,
  },
  {
    id: 5,
    name: "Dell XPS 13",
    category: "Laptops",
    brand: "Dell",
    price: 1299,
    discountPrice: 1199,
    rating: 4.5,
    reviews: 67,
    image: "/dell-xps-13-laptop-silver.jpg",
    tag: "Popular",
    inStock: true,
  },
  {
    id: 6,
    name: "iPad Pro 12.9",
    category: "Tablets",
    brand: "Apple",
    price: 1099,
    discountPrice: null,
    rating: 4.8,
    reviews: 94,
    image: "/ipad-pro-tablet-space-gray.jpg",
    tag: "Professional",
    inStock: false,
  },
  {
    id: 7,
    name: "Sony WH-1000XM5",
    category: "Audio",
    brand: "Sony",
    price: 399,
    discountPrice: 349,
    rating: 4.7,
    reviews: 178,
    image: "/sony-headphones-black-wireless.jpg",
    tag: "Premium",
    inStock: true,
  },
  {
    id: 8,
    name: "Google Pixel 8 Pro",
    category: "Smartphones",
    brand: "Google",
    price: 999,
    discountPrice: 899,
    rating: 4.6,
    reviews: 112,
    image: "/google-pixel-8-pro-smartphone.jpg",
    tag: "AI Powered",
    inStock: true,
  },
  {
    id: 9,
    name: "Surface Laptop 5",
    category: "Laptops",
    brand: "Microsoft",
    price: 1599,
    discountPrice: null,
    rating: 4.4,
    reviews: 45,
    image: "/microsoft-surface-laptop-platinum.jpg",
    tag: "Business",
    inStock: true,
  },
  {
    id: 10,
    name: "Samsung Galaxy Tab S9",
    category: "Tablets",
    brand: "Samsung",
    price: 799,
    discountPrice: 699,
    rating: 4.5,
    reviews: 87,
    image: "/samsung-galaxy-tab-s9-tablet.jpg",
    tag: "Creative",
    inStock: true,
  },
  {
    id: 11,
    name: "Bose QuietComfort 45",
    category: "Audio",
    brand: "Bose",
    price: 329,
    discountPrice: 279,
    rating: 4.6,
    reviews: 145,
    image: "/bose-quietcomfort-headphones-black.jpg",
    tag: "Noise Cancelling",
    inStock: true,
  },
  {
    id: 12,
    name: "OnePlus 12",
    category: "Smartphones",
    brand: "OnePlus",
    price: 899,
    discountPrice: 799,
    rating: 4.5,
    reviews: 98,
    image: "/oneplus-12-smartphone-green.jpg",
    tag: "Fast Charging",
    inStock: true,
  },
];
